all: projet
projetprelim: Plateau.o Case.o main.cpp
	g++ Plateau.o Case.o main.cpp -o projetprelim	
Plateau.o: Plateau.cpp
	g++ -c Plateau.cpp
Case.o: Case.cpp
	g++ -c Case.cpp


projet:
	echo "Modifiez le fichier Makefile pour permettre la compilation de votre projet"
projetgraph:
	echo "Modifiez le fichier Makefile pour permettre la compilation de votre projet"
clean: 
	rm *.o
